# Generated by Django 3.1.3 on 2023-06-06 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0008_answerhistory_commenthistory_questionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerhistory',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pybo.answer'),
        ),
        migrations.AlterField(
            model_name='commenthistory',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pybo.comment'),
        ),
        migrations.AlterField(
            model_name='questionhistory',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pybo.question'),
        ),
    ]
